# Loading a csv into DataFrame

In [2]:
import pandas as pd

df = pd.read_csv("WineQT.csv")

print(df.head())
print(df.info())
print(df.describe())
print(df.shape)

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076
1            7.8              0.88         0.00             2.6      0.098
2            7.8              0.76         0.04             2.3      0.092
3           11.2              0.28         0.56             1.9      0.075
4            7.4              0.70         0.00             1.9      0.076

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56
1                 25.0                  67.0   0.9968  3.20       0.68
2                 15.0                  54.0   0.9970  3.26       0.65
3                 17.0                  60.0   0.9980  3.16       0.58
4                 11.0                  34.0   0.9978  3.51       0.56

   alcohol  quality  Id
0      9.4        5   0
1      9.8        5   1
2      9.8        5   2
3      9.8        6   3
4      9.4        5   4
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB
None
       fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1143.000000       1143.000000  1143.000000     1143.000000
mean        8.311111          0.531339     0.268364        2.532152
std         1.747595          0.179633     0.196686        1.355917
min         4.600000          0.120000     0.000000        0.900000
25%         7.100000          0.392500     0.090000        1.900000
50%         7.900000          0.520000     0.250000        2.200000
75%         9.100000          0.640000     0.420000        2.600000
max        15.900000          1.580000     1.000000       15.500000

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1143.000000          1143.000000           1143.000000  1143.000000
mean      0.086933            15.615486             45.914698     0.996730
std       0.047267            10.250486             32.782130     0.001925
min       0.012000             1.000000              6.000000     0.990070
25%       0.070000             7.000000             21.000000     0.995570
50%       0.079000            13.000000             37.000000     0.996680
75%       0.090000            21.000000             61.000000     0.997845
max       0.611000            68.000000            289.000000     1.003690

                pH    sulphates      alcohol      quality           Id
count  1143.000000  1143.000000  1143.000000  1143.000000  1143.000000
mean      3.311015     0.657708    10.442111     5.657043   804.969379
std       0.156664     0.170399     1.082196     0.805824   463.997116
min       2.740000     0.330000     8.400000     3.000000     0.000000
25%       3.205000     0.550000     9.500000     5.000000   411.000000
50%       3.310000     0.620000    10.200000     6.000000   794.000000
75%       3.400000     0.730000    11.100000     6.000000  1209.500000
max       4.010000     2.000000    14.900000     8.000000  1597.000000
(1143, 13)

###

In [9]:
# print all rows with columns alcohol and quality
df.loc[:, ["alcohol", "quality"]]

      alcohol  quality
0         9.4        5
1         9.8        5
2         9.8        5
3         9.8        6
4         9.4        5
...       ...      ...
1138     11.0        6
1139      9.5        6
1140     10.5        5
1141     11.2        6
1142     10.2        5

[1143 rows x 2 columns]

In [8]:
# print five rows with columns alcohol and quality
df.loc[0:4, ["alcohol", "quality"]]

   alcohol  quality
0      9.4        5
1      9.8        5
2      9.8        5
3      9.8        6
4      9.4        5

In [10]:
# Retrieving data with index
# First 5 rows aur first 3 columns:
df.iloc[0:5, 0:3]

   fixed acidity  volatile acidity  citric acid
0            7.4              0.70         0.00
1            7.8              0.88         0.00
2            7.8              0.76         0.04
3           11.2              0.28         0.56
4            7.4              0.70         0.00

In [11]:
# First row
df.iloc[0]

fixed acidity            7.4000
volatile acidity         0.7000
citric acid              0.0000
residual sugar           1.9000
chlorides                0.0760
free sulfur dioxide     11.0000
total sulfur dioxide    34.0000
density                  0.9978
pH                       3.5100
sulphates                0.5600
alcohol                  9.4000
quality                  5.0000
Id                       0.0000
Name: 0, dtype: float64

# Boolean Filtering

In [12]:
# Print the data where alcohol > 12
df[df["alcohol"] > 12]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
32,4.6,0.52,0.15,2.1,0.054,8.0,65.0,0.99340,3.90,0.56,13.100000,4,45
91,5.6,0.50,0.09,2.3,0.049,17.0,99.0,0.99370,3.63,0.63,13.000000,5,131
96,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.000000,6,142
98,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.000000,6,144
148,9.7,0.53,0.60,2.0,0.039,5.0,19.0,0.99585,3.30,0.86,12.400000,6,210
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1052,5.3,0.47,0.11,2.2,0.048,16.0,89.0,0.99182,3.54,0.88,13.566667,7,1475
1054,5.3,0.47,0.11,2.2,0.048,16.0,89.0,0.99182,3.54,0.88,13.600000,7,1477
1064,7.1,0.22,0.49,1.8,0.039,8.0,18.0,0.99344,3.39,0.56,12.400000,6,1490
1122,6.4,0.36,0.53,2.2,0.230,19.0,35.0,0.99340,3.37,0.93,12.400000,6,1570
1125,6.0,0.58,0.20,2.4,0.075,15.0,50.0,0.99467,3.58,0.67,12.500000,6,1573

In [13]:
# Multiple Condition (AND)
df[(df["alcohol"] > 12) & (df["quality"] >= 7)]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
162,5.2,0.480,0.04,1.6,0.054,19.0,106.0,0.99270,3.54,0.62,12.200000,7,230
190,7.9,0.350,0.46,3.6,0.078,15.0,37.0,0.99730,3.35,0.86,12.800000,8,267
197,10.3,0.320,0.45,6.4,0.073,5.0,13.0,0.99760,3.23,0.82,12.600000,8,278
237,11.9,0.695,0.53,3.4,0.128,7.0,21.0,0.99920,3.17,0.84,12.200000,7,335
271,5.6,0.850,0.05,1.4,0.045,12.0,88.0,0.99240,3.56,0.82,12.900000,8,390
274,12.0,0.370,0.76,4.2,0.066,7.0,38.0,1.00040,3.22,0.60,13.000000,7,395
294,6.6,0.840,0.03,2.3,0.059,32.0,48.0,0.99520,3.52,0.56,12.300000,7,421
297,6.6,0.840,0.03,2.3,0.059,32.0,48.0,0.99520,3.52,0.56,12.300000,7,425
312,5.3,0.570,0.01,1.7,0.054,5.0,27.0,0.99340,3.57,0.84,12.500000,7,444
321,11.3,0.620,0.67,5.2,0.086,6.0,19.0,0.99880,3.22,0.69,13.400000,8,455
345,9.2,0.410,0.50,2.5,0.055,12.0,25.0,0.99520,3.34,0.79,13.300000,7,491
346,8.9,0.400,0.51,2.6,0.052,13.0,27.0,0.99500,3.32,0.90,13.400000,7,492
358,10.2,0.490,0.63,2.9,0.072,10.0,26.0,0.99680,3.16,0.78,12.500000,7,505
419,5.0,0.420,0.24,2.0,0.060,19.0,50.0,0.99170,3.72,0.74,14.000000,8,588
577,5.1,0.585,0.00,1.7,0.044,14.0,86.0,0.99264,3.56,0.94,12.900000,7,802
580,8.4,0.250,0.39,2.0,0.041,4.0,10.0,0.99386,3.27,0.71,12.500000,7,806
589,4.9,0.420,0.00,2.1,0.048,16.0,42.0,0.99154,3.71,0.74,14.000000,7,821
633,8.3,0.310,0.39,2.4,0.078,17.0,43.0,0.99444,3.31,0.77,12.500000,7,896
635,8.3,0.310,0.39,2.4,0.078,17.0,43.0,0.99444,3.31,0.77,12.500000,7,898
664,9.9,0.270,0.49,5.0,0.082,9.0,17.0,0.99484,3.19,0.52,12.500000,7,941
666,8.3,0.300,0.49,3.8,0.090,11.0,24.0,0.99498,3.27,0.64,12.100000,7,944
668,8.3,0.280,0.48,2.1,0.093,6.0,12.0,0.99408,3.26,0.62,12.400000,7,947
671,8.3,0.280,0.48,2.1,0.093,6.0,12.0,0.99408,3.26,0.62,12.400000,7,951
673,10.2,0.340,0.48,2.1,0.052,5.0,9.0,0.99458,3.20,0.69,12.100000,7,953
684,8.8,0.330,0.41,5.9,0.073,7.0,13.0,0.99658,3.30,0.62,12.100000,7,974
704,6.8,0.360,0.32,1.8,0.067,4.0,8.0,0.99280,3.36,0.55,12.800000,7,1005
708,8.9,0.280,0.45,1.7,0.067,7.0,12.0,0.99354,3.25,0.55,12.300000,7,1010
713,8.9,0.380,0.40,2.2,0.068,12.0,28.0,0.99486,3.27,0.75,12.600000,7,1016
728,7.6,0.310,0.34,2.5,0.082,26.0,35.0,0.99356,3.22,0.59,12.500000,7,1036
729,8.7,0.410,0.41,6.2,0.078,25.0,42.0,0.99530,3.24,0.77,12.600000,7,1038
740,8.3,0.330,0.42,2.3,0.070,9.0,20.0,0.99426,3.38,0.77,12.700000,7,1053
742,8.9,0.480,0.53,4.0,0.101,3.0,10.0,0.99586,3.21,0.59,12.100000,7,1056
745,8.9,0.480,0.53,4.0,0.101,3.0,10.0,0.99586,3.21,0.59,12.100000,7,1059
747,9.1,0.400,0.50,1.8,0.071,7.0,16.0,0.99462,3.21,0.69,12.500000,8,1061
752,6.6,0.520,0.08,2.4,0.070,13.0,26.0,0.99358,3.40,0.72,12.500000,7,1066
760,7.9,0.300,0.68,8.3,0.050,37.5,278.0,0.99316,3.01,0.51,12.300000,7,1079
761,7.9,0.300,0.68,8.3,0.050,37.5,289.0,0.99316,3.01,0.51,12.300000,7,1081
785,5.4,0.420,0.27,2.0,0.092,23.0,55.0,0.99471,3.78,0.64,12.300000,7,1111
793,7.9,0.540,0.34,2.5,0.076,8.0,17.0,0.99235,3.20,0.72,13.100000,8,1120
799,7.4,0.360,0.34,1.8,0.075,18.0,38.0,0.99330,3.38,0.88,13.600000,7,1132
821,5.1,0.510,0.18,2.1,0.042,16.0,101.0,0.99240,3.46,0.87,12.900000,7,1157
824,8.2,0.330,0.39,2.5,0.074,29.0,48.0,0.99528,3.32,0.88,12.400000,7,1167
842,7.2,0.250,0.37,2.5,0.063,11.0,41.0,0.99439,3.52,0.80,12.400000,7,1192
868,5.1,0.420,0.00,1.8,0.044,18.0,88.0,0.99157,3.68,0.73,13.600000,7,1228
1000,8.1,0.290,0.36,2.2,0.048,35.0,53.0,0.99500,3.27,1.01,12.400000,7,1408
1009,7.3,0.340,0.33,2.5,0.064,21.0,37.0,0.99520,3.35,0.77,12.100000,7,1417
1052,5.3,0.470,0.11,2.2,0.048,16.0,89.0,0.99182,3.54,0.88,13.566667,7,1475
1054,5.3,0.470,0.11,2.2,0.048,16.0,89.0,0.99182,3.54,0.88,13.600000,7,1477

In [14]:
# Multiple Condition (OR)
df[(df["alcohol"] > 13) | (df["quality"] >= 8)]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
32,4.6,0.520,0.15,2.1,0.054,8.0,65.0,0.99340,3.90,0.56,13.100000,4,45
96,5.2,0.340,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.000000,6,142
98,5.2,0.340,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.000000,6,144
190,7.9,0.350,0.46,3.6,0.078,15.0,37.0,0.99730,3.35,0.86,12.800000,8,267
197,10.3,0.320,0.45,6.4,0.073,5.0,13.0,0.99760,3.23,0.82,12.600000,8,278
267,11.4,0.625,0.66,6.2,0.088,6.0,24.0,0.99880,3.11,0.99,13.300000,6,378
271,5.6,0.850,0.05,1.4,0.045,12.0,88.0,0.99240,3.56,0.82,12.900000,8,390
310,12.6,0.310,0.72,2.2,0.072,6.0,29.0,0.99870,2.88,0.82,9.800000,8,440
321,11.3,0.620,0.67,5.2,0.086,6.0,19.0,0.99880,3.22,0.69,13.400000,8,455
329,8.8,0.460,0.45,2.6,0.065,7.0,18.0,0.99470,3.32,0.79,14.000000,6,467
340,9.4,0.300,0.56,2.8,0.080,6.0,17.0,0.99640,3.15,0.92,11.700000,8,481
345,9.2,0.410,0.50,2.5,0.055,12.0,25.0,0.99520,3.34,0.79,13.300000,7,491
346,8.9,0.400,0.51,2.6,0.052,13.0,27.0,0.99500,3.32,0.90,13.400000,7,492
349,10.7,0.350,0.53,2.6,0.070,5.0,16.0,0.99720,3.15,0.65,11.000000,8,495
352,10.7,0.350,0.53,2.6,0.070,5.0,16.0,0.99720,3.15,0.65,11.000000,8,498
419,5.0,0.420,0.24,2.0,0.060,19.0,50.0,0.99170,3.72,0.74,14.000000,8,588
462,15.9,0.360,0.65,7.5,0.096,22.0,71.0,0.99760,2.98,0.84,14.900000,5,652
589,4.9,0.420,0.00,2.1,0.048,16.0,42.0,0.99154,3.71,0.74,14.000000,7,821
643,9.3,0.380,0.48,3.8,0.132,3.0,11.0,0.99577,3.23,0.57,13.200000,6,910
747,9.1,0.400,0.50,1.8,0.071,7.0,16.0,0.99462,3.21,0.69,12.500000,8,1061
769,10.0,0.260,0.54,1.9,0.083,42.0,74.0,0.99451,2.98,0.63,11.800000,8,1090
787,5.0,0.400,0.50,4.3,0.046,29.0,80.0,0.99020,3.49,0.66,13.600000,6,1114
791,7.1,0.390,0.12,2.1,0.065,14.0,24.0,0.99252,3.30,0.53,13.300000,6,1118
793,7.9,0.540,0.34,2.5,0.076,8.0,17.0,0.99235,3.20,0.72,13.100000,8,1120
799,7.4,0.360,0.34,1.8,0.075,18.0,38.0,0.99330,3.38,0.88,13.600000,7,1132
850,8.6,0.420,0.39,1.8,0.068,6.0,12.0,0.99516,3.35,0.69,11.700000,8,1202
868,5.1,0.420,0.00,1.8,0.044,18.0,88.0,0.99157,3.68,0.73,13.600000,7,1228
898,5.0,0.380,0.01,1.6,0.048,26.0,60.0,0.99084,3.70,0.75,14.000000,6,1270
996,7.2,0.330,0.33,1.7,0.061,3.0,13.0,0.99600,3.23,1.10,10.000000,8,1403
1030,7.2,0.380,0.31,2.0,0.056,15.0,29.0,0.99472,3.23,0.76,11.300000,8,1449
1052,5.3,0.470,0.11,2.2,0.048,16.0,89.0,0.99182,3.54,0.88,13.566667,7,1475
1054,5.3,0.470,0.11,2.2,0.048,16.0,89.0,0.99182,3.54,0.88,13.600000,7,1477
1104,7.4,0.360,0.30,1.8,0.074,17.0,24.0,0.99419,3.24,0.70,11.400000,8,1549

In [15]:
# Data of alcohol and quality where alcohol > 12
df.loc[df["alcohol"] > 12, ["alcohol", "quality"]]

        alcohol  quality
32    13.100000        4
91    13.000000        5
96    14.000000        6
98    14.000000        6
148   12.400000        6
...         ...      ...
1052  13.566667        7
1054  13.600000        7
1064  12.400000        6
1122  12.400000        6
1125  12.500000        6

[103 rows x 2 columns]

# Creating new columns with existing columns

In [18]:
# Creating alcohol_density_ratio column with alcohol and density column
df["alcohol_density_ratio"] = df["alcohol"] / df["density"]

In [19]:
df[["alcohol", "density", "alcohol_density_ratio"]].head()

   alcohol  density  alcohol_density_ratio
0      9.4   0.9978               9.420726
1      9.8   0.9968               9.831461
2      9.8   0.9970               9.829488
3      9.8   0.9980               9.819639
4      9.4   0.9978               9.420726

# GroupBY() + Aggregation

In [24]:
#. groupby() + mean()
print("Average alcohol of each quality level")
df.groupby("quality")["alcohol"].mean()

Average alcohol of each quality level

quality
3     9.691667
4    10.260606
5     9.902277
6    10.655339
7    11.482634
8    11.937500
Name: alcohol, dtype: float64

In [25]:
# groupby() + count()
df.groupby("quality")["alcohol"].count()

quality
3      6
4     33
5    483
6    462
7    143
8     16
Name: alcohol, dtype: int64

In [29]:
# groupby()  + mean + count
df.groupby("quality")["alcohol"].agg(["mean", "count"])

              mean  count
quality
3         9.691667      6
4        10.260606     33
5         9.902277    483
6        10.655339    462
7        11.482634    143
8        11.937500     16

In [30]:
quality_summary = df.groupby("quality")["alcohol"].agg(
    mean_alcohol="mean",
    wine_count="count"
)

print(quality_summary)

         mean_alcohol  wine_count
quality
3            9.691667           6
4           10.260606          33
5            9.902277         483
6           10.655339         462
7           11.482634         143
8           11.937500          16

# Merge()

In [31]:
# Creating two DataFrames
df1 = df[["Id", "quality"]].copy()

df2 = df[["Id", "alcohol"]].copy()

In [33]:
# Merging the DataFrames
merged_df = pd.merge(df1, df2, on="Id")
print(merged_df.head())

   Id  quality  alcohol
0   0        5      9.4
1   1        5      9.8
2   2        5      9.8
3   3        6      9.8
4   4        5      9.4

In [34]:
# Merging and comparing the row count
df1 = df[["Id", "quality"]].copy()
df2 = df[["Id", "alcohol"]].copy()

merged_df = pd.merge(df1, df2, on="Id")

print(merged_df.head())
print("Original rows:", len(df))
print("Merged rows:", len(merged_df))

   Id  quality  alcohol
0   0        5      9.4
1   1        5      9.8
2   2        5      9.8
3   3        6      9.8
4   4        5      9.4
Original rows: 1143
Merged rows: 1143